services:
  - type: web
    name: loadpulse
    runtime: node
    buildCommand: npm install && cd web && npm run build && cp -r .next/static .next/standalone/web/.next/static && cp -r public .next/standalone/web/public
    startCommand: cd web && node .next/standalone/web/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
